---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: bitwarden-k8s-secrets-manager build
  name: bitwarden-k8s-secrets-manager-build

parameters:
- name: KOPF_S2I_IMAGE
  value: quay.io/redhat-cop/python-kopf-s2i:v1.37
- name: GIT_REPO
  value: https://github.com/rhpds/bitwarden-k8s-secrets-manager.git
- name: NAME
  value: bitwarden-k8s-secrets-manager

objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: ${NAME}
  spec:
    lookupPolicy:
      local: false

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: ${GIT_REPO}
        ref: master
    strategy:
      type: Source
      dockerStrategy:
        dockerfilePath: Containerfile
        from:
          kind: DockerImage
          name: ${KOPF_S2I_IMAGE}
    triggers: []
