{{ if .Values.deploy }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bitwarden-k8s-secrets-manager.serviceAccountName" . }}
  namespace: {{ include "bitwarden-k8s-secrets-manager.namespaceName" . }}
  labels:
    {{- include "bitwarden-k8s-secrets-manager.labels" . | nindent 4 }}
{{ end }}
