apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: bitwardensyncsecrets.bitwarden-k8s-secrets-manager.demo.redhat.com
spec:
  group: bitwarden-k8s-secrets-manager.demo.redhat.com
  scope: Namespaced
  names:
    plural: bitwardensyncsecrets
    singular: bitwardensyncsecret
    kind: BitwardenSyncSecret
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        description: >-
          Secret configuration for bitwarden-k8s-secrets-manager
        type: object
        required:
        - apiVersion
        - kind
        - metadata
        - spec
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
            properties:
              name:
                type: string
                maxLength: 63
                pattern: ^[a-z0-9\-]*[a-z0-9]$
          spec:
            description: >-
              Kubernetes Secret configuration to extend BitwardenSyncConfig secrets list.
            type: object
            required:
            - data
            properties:
              config:
                description: >-
                  BitwardenSyncConfig name for this secret.
                type: object
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
              annotations:
                type: object
                additionalProperties:
                  type: object
                  properties:
                    key:
                      type: string
                    project:
                      type: string
                    secret:
                      type: string
                    value:
                      type: string
                  required:
                  - secret
              data:
                type: object
                additionalProperties:
                  type: object
                  properties:
                    key:
                      type: string
                    project:
                      type: string
                    secret:
                      type: string
                    value:
                      type: string
                  required:
                  - secret
              labels:
                type: object
                additionalProperties:
                  type: object
                  properties:
                    key:
                      type: string
                    project:
                      type: string
                    secret:
                      type: string
                    value:
                      type: string
                  required:
                  - secret
              type:
                type: string
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
